"""empty message

Revision ID: 73e10ea88401
Revises: d3c32d203ef1
Create Date: 2023-06-16 10:45:37.103571

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '73e10ea88401'
down_revision = 'd3c32d203ef1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_forms', sa.Column('min', sa.Integer(), nullable=True))
    op.add_column('custom_forms', sa.Column('max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_forms', 'max')
    op.drop_column('custom_forms', 'min')
    # ### end Alembic commands ###
